### ISSUE TITLE
proprietary FCI item warning

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#49] opened 2016-04-19 22:58 UTC
OK, I was a bit too quick about that warning - just used different cards: This is the warning I'm getting:

WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI proprietary data: 9F6E06479120813B00

... and this site https://www.eftlab.co.uk/index.php/site-map/knowledge-base/145-emv-nfc-tags says:
Third Party Data - The Third Party Data contains various information, possibly including information from a third party. If present in the Card, the Third Party Data must be returned in a file read using the READ RECORD command or in the File Control Information Template. 'Device Type' is present when the most significant bit of byte 1 of 'Unique Identifier' is set to 0b. In this case, the maximum length of 'Proprietary Data' is 26 bytes. Otherwise it is 28 bytes.

**Comment by martinpaljak** [comment] 2016-04-20 06:59
This specific tag should be handled with DEBUG level already? See https://github.com/martinpaljak/GlobalPlatformPro/blob/master/src/pro/javacard/gp/GlobalPlatform.java#L289

**Comment by dancvrcek** [comment] 2016-04-20 07:32
It ends up as a warning 3 lines lower - just wondered why this level, rather than info or debug? 

Mo pressure, more curiosity. :)

**Comment by martinpaljak** [comment] 2016-04-20 08:42
Correct, warn is not justified. But it should not reach the code three
lines below, but shall check in more detail ASAP.

**Comment by martinpaljak** [comment] 2016-07-01 07:12
Due to work, vacations and summer these things have stalled a bit. Can you give a kick by checking the latest master and if it still misbehaves ?

**Comment by dancvrcek** [comment] 2016-07-01 08:39
I believe you can close it - log re-classified in b838b30 - seems to be behaved now

**Comment by joostrijneveld** [comment] 2017-08-16 12:34
I can confirm a similar warning (albeit with slightly different 'proprietary data') when using the latest release, as well as the fact that the latest `master` ([`de4aa8e`](https://github.com/martinpaljak/GlobalPlatformPro/commit/de4aa8e) as of writing this) no longer has this behaviour.

**Comment by martinpaljak** [comment] 2017-08-16 13:09
If the proprietary data can not be parsed by GP and does not affect GP operations, I believe this is the state it will remain. Can you give the specifics ?

**Comment by joostrijneveld** [comment] 2017-08-16 13:19
Specifically I'm getting `[main] WARN pro.javacard.gp.GlobalPlatform - Unknown/unhandled tag in FCI proprietary data: 9F6E06479181023100`. Perhaps I was not really clear: I can reproduce that this has been fixed in the latest HEAD, so I agree with @dancvrcek that this issue can be closed.

**Comment by martinpaljak** [comment] 2017-08-16 15:26
OK, great!

**Closed by martinpaljak** 2017-08-16 15:26 UTC
